apiVersion: apps/v1
kind: Deployment
metadata:
    name: cdf-deploy-test
    labels:
        app: nginx
spec:
    replicas: 4
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - env:
              - name: TEST_ID
                value: "${(new java.util.UUID(0,0)).randomUUID()}"
              - name: APP_NAME
                value: "aurora-${app}-test"
              name: nginx
              image: nginx:1.16.0
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cdf-deploy-test-service
  annotations:
    imageregistry: "test-${app}-${(new java.util.UUID(0,0)).randomUUID()}"
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
