apiVersion: apps/v1
kind: Deployment
metadata:
    name: cdf-deploy-test
    namespace: cdf-dev-agent
    labels:
        app: nginx
spec:
    replicas: 4
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - env:
              - name: TEST_ID
                value: "${(new java.util.UUID(0,0)).randomUUID()}"
              name: nginx
              image: nginx:1.16.0
              ports:
              - containerPort: 80
