apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      source: demo
  template:
    metadata:
      labels:
        app: nginx
        source: demo
    spec:
      containers:
        - image: 'nginx:1.7.9'
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: workdir
      initContainers:
        - command:
            - wget
            - '-O'
            - /work-dir/index.html
            - 'http://kubernetes.io'
          image: busybox
          name: install
          volumeMounts:
            - mountPath: /work-dir
              name: workdir
      volumes:
        - emptyDir: {}
          name: workdir
---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-demosss
spec:
  ports:
    - port: 8765
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
    source: demo
  type: LoadBalancer
