apiVersion: apps/v1
kind: Deployment
metadata:
    name: cdf-deploy-test
    labels:
        app: nginx
spec: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cdf-deploy-test-service
  annotations:
    imageregistry: "test-${app}-${(new java.util.UUID(0,0)).randomUUID()}"
  labels:
    app: svc-spinnaker-demo
    app.kubernetes.io/name: svc-spinnaker-demo
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: svc-spinnaker-demo
    tags.datadoghq.com/version: "${#stage('Evaluate Variables')['context']['ttype']}"
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
